// GENERATED by build extraction — do not edit by hand.
import fx_gradient from './effects/shader/gradient.js';
import fx_dots from './effects/shader/dots.js';
import fx_metaballs from './effects/shader/metaballs.js';
import fx_aurora from './effects/shader/aurora.js';
import fx_ripple from './effects/shader/ripple.js';
import fx_voronoi from './effects/shader/voronoi.js';
import fx_truchet from './effects/shader/truchet.js';
import fx_kaleido from './effects/shader/kaleido.js';
import fx_raymarch from './effects/shader/raymarch.js';
import fx_vapor from './effects/shader/vapor.js';
import fx_glitch from './effects/shader/glitch.js';
import fx_field from './effects/canvas/field.js';
import fx_seigaiha from './effects/canvas/seigaiha.js';
import fx_girih from './effects/canvas/girih.js';
import fx_celtic from './effects/canvas/celtic.js';
import fx_aboriginal from './effects/canvas/aboriginal.js';
import fx_inkwash from './effects/canvas/inkwash.js';
import fx_opart from './effects/canvas/opart.js';
import fx_bauhaus from './effects/canvas/bauhaus.js';
import fx_memphis from './effects/canvas/memphis.js';
import fx_matrix from './effects/canvas/matrix.js';
import fx_scope from './effects/canvas/scope.js';
import fx_starfield from './effects/canvas/starfield.js';
import fx_halftone from './effects/canvas/halftone.js';
import fx_ascii from './effects/canvas/ascii.js';
import fx_topo from './effects/canvas/topo.js';
import fx_quasicrystal from './effects/canvas/quasicrystal.js';
import fx_phyllotaxis from './effects/canvas/phyllotaxis.js';
import fx_rose from './effects/canvas/rose.js';
import fx_spiro from './effects/canvas/spiro.js';
import fx_lissajous from './effects/canvas/lissajous.js';
import fx_superformula from './effects/canvas/superformula.js';
import fx_hexgrid from './effects/canvas/hexgrid.js';
import fx_concentric from './effects/canvas/concentric.js';
import fx_spiralarc from './effects/canvas/spiralarc.js';
import fx_interference from './effects/canvas/interference.js';
import fx_chevron from './effects/canvas/chevron.js';
import fx_herringbone from './effects/canvas/herringbone.js';
import fx_polka from './effects/canvas/polka.js';
import fx_houndstooth from './effects/canvas/houndstooth.js';
import fx_plaid from './effects/canvas/plaid.js';
import fx_starburst from './effects/canvas/starburst.js';
import fx_wavelines from './effects/canvas/wavelines.js';
import fx_mandelbrot from './effects/canvas/mandelbrot.js';
import fx_julia from './effects/canvas/julia.js';
import fx_clifford from './effects/canvas/clifford.js';
import fx_dejong from './effects/canvas/dejong.js';
import fx_lorenz from './effects/canvas/lorenz.js';
import fx_fern from './effects/canvas/fern.js';
import fx_sierpinski from './effects/canvas/sierpinski.js';
import fx_dragon from './effects/canvas/dragon.js';
import fx_fractaltree from './effects/canvas/fractaltree.js';
import fx_life from './effects/canvas/life.js';
import fx_briansbrain from './effects/canvas/briansbrain.js';
import fx_langton from './effects/canvas/langton.js';
import fx_boids from './effects/canvas/boids.js';
import fx_doomfire from './effects/canvas/doomfire.js';
import fx_sandfall from './effects/canvas/sandfall.js';
import fx_pendulum from './effects/canvas/pendulum.js';
import fx_orbits from './effects/canvas/orbits.js';
import fx_asanoha from './effects/canvas/asanoha.js';
import fx_kolam from './effects/canvas/kolam.js';
import fx_greekkey from './effects/canvas/greekkey.js';
import fx_aztec from './effects/canvas/aztec.js';
import fx_kente from './effects/canvas/kente.js';
import fx_talavera from './effects/canvas/talavera.js';
import fx_cloud from './effects/canvas/cloud.js';
import fx_koru from './effects/canvas/koru.js';
import fx_paisley from './effects/canvas/paisley.js';
import fx_tunnel from './effects/canvas/tunnel.js';
import fx_plasma from './effects/canvas/plasma.js';
import fx_rotozoom from './effects/canvas/rotozoom.js';
import fx_copperbars from './effects/canvas/copperbars.js';
import fx_sevenseg from './effects/canvas/sevenseg.js';
import fx_ledmatrix from './effects/canvas/ledmatrix.js';
import fx_radar from './effects/canvas/radar.js';
import fx_ekg from './effects/canvas/ekg.js';
import fx_cursortrail from './effects/canvas/cursortrail.js';
import fx_crosshair from './effects/canvas/crosshair.js';
import fx_ripplewater from './effects/canvas/ripplewater.js';
import fx_blobcursor from './effects/canvas/blobcursor.js';
import fx_ironfilings from './effects/canvas/ironfilings.js';
import fx_vortex from './effects/canvas/vortex.js';
import fx_confetti from './effects/canvas/confetti.js';
import fx_fireworks from './effects/canvas/fireworks.js';
import fx_bokeh from './effects/canvas/bokeh.js';
import fx_nebula from './effects/canvas/nebula.js';
import fx_lightning from './effects/canvas/lightning.js';
import fx_neonpipes from './effects/canvas/neonpipes.js';
import fx_spinners from './effects/canvas/spinners.js';
import fx_wavegrid from './effects/canvas/wavegrid.js';
import fx_audiobars from './effects/canvas/audiobars.js';
import fx_heatmap from './effects/canvas/heatmap.js';
import fx_scramble from './effects/dom/scramble.js';
import fx_magnetic from './effects/dom/magnetic.js';
import fx_kinetic from './effects/dom/kinetic.js';
import fx_marquee from './effects/dom/marquee.js';
import fx_tilt from './effects/dom/tilt.js';
import fx_spot from './effects/dom/spot.js';

export const REGISTRY = {
  "gradient": fx_gradient,
  "dots": fx_dots,
  "metaballs": fx_metaballs,
  "aurora": fx_aurora,
  "ripple": fx_ripple,
  "voronoi": fx_voronoi,
  "truchet": fx_truchet,
  "kaleido": fx_kaleido,
  "raymarch": fx_raymarch,
  "vapor": fx_vapor,
  "glitch": fx_glitch,
  "field": fx_field,
  "seigaiha": fx_seigaiha,
  "girih": fx_girih,
  "celtic": fx_celtic,
  "aboriginal": fx_aboriginal,
  "inkwash": fx_inkwash,
  "opart": fx_opart,
  "bauhaus": fx_bauhaus,
  "memphis": fx_memphis,
  "matrix": fx_matrix,
  "scope": fx_scope,
  "starfield": fx_starfield,
  "halftone": fx_halftone,
  "ascii": fx_ascii,
  "topo": fx_topo,
  "quasicrystal": fx_quasicrystal,
  "phyllotaxis": fx_phyllotaxis,
  "rose": fx_rose,
  "spiro": fx_spiro,
  "lissajous": fx_lissajous,
  "superformula": fx_superformula,
  "hexgrid": fx_hexgrid,
  "concentric": fx_concentric,
  "spiralarc": fx_spiralarc,
  "interference": fx_interference,
  "chevron": fx_chevron,
  "herringbone": fx_herringbone,
  "polka": fx_polka,
  "houndstooth": fx_houndstooth,
  "plaid": fx_plaid,
  "starburst": fx_starburst,
  "wavelines": fx_wavelines,
  "mandelbrot": fx_mandelbrot,
  "julia": fx_julia,
  "clifford": fx_clifford,
  "dejong": fx_dejong,
  "lorenz": fx_lorenz,
  "fern": fx_fern,
  "sierpinski": fx_sierpinski,
  "dragon": fx_dragon,
  "fractaltree": fx_fractaltree,
  "life": fx_life,
  "briansbrain": fx_briansbrain,
  "langton": fx_langton,
  "boids": fx_boids,
  "doomfire": fx_doomfire,
  "sandfall": fx_sandfall,
  "pendulum": fx_pendulum,
  "orbits": fx_orbits,
  "asanoha": fx_asanoha,
  "kolam": fx_kolam,
  "greekkey": fx_greekkey,
  "aztec": fx_aztec,
  "kente": fx_kente,
  "talavera": fx_talavera,
  "cloud": fx_cloud,
  "koru": fx_koru,
  "paisley": fx_paisley,
  "tunnel": fx_tunnel,
  "plasma": fx_plasma,
  "rotozoom": fx_rotozoom,
  "copperbars": fx_copperbars,
  "sevenseg": fx_sevenseg,
  "ledmatrix": fx_ledmatrix,
  "radar": fx_radar,
  "ekg": fx_ekg,
  "cursortrail": fx_cursortrail,
  "crosshair": fx_crosshair,
  "ripplewater": fx_ripplewater,
  "blobcursor": fx_blobcursor,
  "ironfilings": fx_ironfilings,
  "vortex": fx_vortex,
  "confetti": fx_confetti,
  "fireworks": fx_fireworks,
  "bokeh": fx_bokeh,
  "nebula": fx_nebula,
  "lightning": fx_lightning,
  "neonpipes": fx_neonpipes,
  "spinners": fx_spinners,
  "wavegrid": fx_wavegrid,
  "audiobars": fx_audiobars,
  "heatmap": fx_heatmap,
  "scramble": fx_scramble,
  "magnetic": fx_magnetic,
  "kinetic": fx_kinetic,
  "marquee": fx_marquee,
  "tilt": fx_tilt,
  "spot": fx_spot,
};

export const IDS = Object.keys(REGISTRY);
